USE [master]
GO

DROP DATABASE IF EXISTS PROYECTO
GO

CREATE DATABASE PROYECTO
GO 

USE PROYECTO

--TABLA CONFIGURACION
CREATE TABLE TBL_CONFIGURACION(
	ID INT IDENTITY(1,1),
	NOMBRE_CONFIGURACION NVARCHAR(30),
	VALOR INT,
	CONSTRAINT PK_ID_CONFIGURACION PRIMARY KEY CLUSTERED (ID)
)

--TABLA COMERCIO
CREATE TABLE TBL_COMERCIO(
	ID INT IDENTITY(1,1),
	NOMBRE NVARCHAR(30),
	NOMBRE_LEGAL NVARCHAR(50),
	CEDULA_JURIDICA NVARCHAR(50),
	ESTADO INT,
	CONSTRAINT PK_ID_COMERCIO PRIMARY KEY CLUSTERED(ID)
)

CREATE UNIQUE NONCLUSTERED INDEX IX_CEDULA_JURIDICA ON TBL_COMERCIO(CEDULA_JURIDICA)

--TABLE ARCHIVOS
CREATE TABLE TBL_ARCHIVOS(
	ID INT IDENTITY(1,1),
	NOMBRE NVARCHAR(30),
	ENLACE NVARCHAR(500),
	TIPO NVARCHAR(15),
	ID_COMERCIO INT,
	CONSTRAINT PK_ID_ARCHIVOS PRIMARY KEY CLUSTERED(ID),
	CONSTRAINT FK_ID_COMERCIO_ARCHIVOS FOREIGN KEY(ID_COMERCIO)
		REFERENCES TBL_COMERCIO(ID)
)

--TABLA USUARIO
CREATE TABLE TBL_USUARIO(
	ID INT IDENTITY(1,1),
	CEDULA NVARCHAR(30),
	NOMBRE NVARCHAR(25),
	APELLIDO NVARCHAR(50),
	CORREO NVARCHAR(100),
	TELEFONO NVARCHAR(30),
	ID_FOTO INT,
	TELEFONO_CONFIRMADO INT,
	CORREO_CONFIRMADO INT,
	CODIGO_TELEFONO NVARCHAR(8),
	CODIGO_CORREO NVARCHAR(8),
	ESTADO INT,
	TIPO INT,
	ID_COMERCIO INT,
	CONSTRAINT PK_ID_USUARIO PRIMARY KEY CLUSTERED(ID),
	CONSTRAINT FK_ID_FOTO FOREIGN KEY(ID_FOTO)
		REFERENCES TBL_ARCHIVOS(ID),
	CONSTRAINT FK_ID_COMERCIO FOREIGN KEY(ID_COMERCIO)
		REFERENCES TBL_COMERCIO(ID)
)

CREATE UNIQUE NONCLUSTERED INDEX IX_CEDULA_PERSONA ON TBL_USUARIO(CEDULA)

CREATE UNIQUE NONCLUSTERED INDEX IX_CORREO_USUARIO ON TBL_USUARIO(CORREO)

--TABLA PROVINCIA
Create table TBL_PROVINCIA(
	codigo NVARCHAR(2) primary key,
	nombre varchar(50) unique
)

--TABLA CANTON
create table TBL_CANTON(
	codigoProvincia NVARCHAR(2) references TBL_PROVINCIA,
	codigo NVARCHAR(2),
	primary key(codigoProvincia, codigo),
	nombre varchar(50)
)

--TABLA DISTRITO
create table TBL_DISTRITO(
	codigoProvincia NVARCHAR(2),
	codigoCanton NVARCHAR(2),
	foreign key(codigoProvincia,codigoCanton) references TBL_CANTON,
	codigo NVARCHAR(2),
	primary key(codigoProvincia,codigoCanton,codigo),
	nombre varchar(50)
)

--TABLA DIRECCION
CREATE TABLE TBL_DIRECCION(
	ID INT IDENTITY(1,1),
	ID_USUARIO INT,
	ID_PROVINCIA NVARCHAR(2), 
	ID_CANTON NVARCHAR(2), 
	ID_DISTRITO NVARCHAR(2),
	DETALLES NVARCHAR(150),
	CONSTRAINT PK_ID_DIRECCION PRIMARY KEY CLUSTERED (ID),
	CONSTRAINT FK_ID_USUARIO_DIRECCION FOREIGN KEY (ID_USUARIO)
		REFERENCES TBL_USUARIO(ID),
	--CONSTRAINT FK_ID_PROVINCIA_DIRECCION FOREIGN KEY(ID_PROVINCIA)
		--REFERENCES TBL_PROVINCIA(codigo),
	--CONSTRAINT FK_ID_CANTON_DIRECCION FOREIGN KEY(ID_CANTON)
		--REFERENCES TBL_CANTON(codigo),
	--CONSTRAINT FK_ID_DISTRITO_DIRECCION FOREIGN KEY(ID_DISTRITO)
		--REFERENCES TBL_DISTRITO(codigo)
)

--TABLA CONTRASENNA
CREATE TABLE TBL_CONTRASENNA(
	ID INT IDENTITY(1,1),
	CONTRASENNA NVARCHAR(15),
	FECHA DATE,
	ID_USUARIO INT,
	CONSTRAINT PK_ID_CONTRASENNA PRIMARY KEY CLUSTERED(ID),
	CONSTRAINT FK_ID_USUARIO_CONTRASENNA FOREIGN KEY (ID_USUARIO)
		REFERENCES TBL_USUARIO(ID)
)



--TABLA HORARIO
CREATE TABLE TBL_HORARIO(
	ID INT IDENTITY(1,1),
	FECHA DATE,
	TIPO_HORARIO NVARCHAR(15),
	HORA_INICIO TIME,
	HORA_FIN TIME,
	ID_USUARIO INT,
	CONSTRAINT PK_ID_HORARIO PRIMARY KEY CLUSTERED(ID),
	CONSTRAINT FK_ID_USUARIO_HORARIO FOREIGN KEY(ID_USUARIO)
		REFERENCES TBL_USUARIO(ID)
)

--TABLA SUCURSAL
CREATE TABLE TBL_SUCURSAL(
	ID INT IDENTITY(1,1),
	NOMBRE NVARCHAR(30),
	LOCALIZACION NVARCHAR(15),
	DETALLES_DIRECCION VARCHAR(300),
	ID_COMERCIO INT, 
	ID_HORARIO INT,
	CONSTRAINT PK_ID_SUCURSAL PRIMARY KEY CLUSTERED(ID),
	CONSTRAINT FK_ID_COMERCIO_SUCURSAL FOREIGN KEY (ID_COMERCIO)
		REFERENCES TBL_COMERCIO(ID),
	CONSTRAINT FK_ID_HORARIO_SUCURSAL FOREIGN KEY (ID_HORARIO)
		REFERENCES TBL_HORARIO(ID)
)

--TABLA IMPUESTO
CREATE TABLE TBL_IMPUESTO(
	ID INT IDENTITY(1,1),
	NOMBRE NVARCHAR(15),
	PORCENTAJE DECIMAL(4,2),
	CONSTRAINT PK_ID_IMPUESTO PRIMARY KEY CLUSTERED(ID)
)

--TABLA ITEM
CREATE TABLE TBL_ITEM(
	ID INT IDENTITY(1,1),
	INVENTARIO INT,
	NOMBRE NVARCHAR(15),
	DESCRIPCION NVARCHAR(300),
	PRECIO DECIMAL(6,2),
	ID_SUCURSAL INT,
	DURACION TIME,
	TIPO NVARCHAR(20),
	ID_IMPUESTO INT,
	ID_FOTO NVARCHAR(500),
	CONSTRAINT PK_ID_ITEM PRIMARY KEY CLUSTERED(ID),
	CONSTRAINT FK_ID_SUCURSAL_ITEM FOREIGN KEY (ID_SUCURSAL)
		REFERENCES TBL_SUCURSAL(ID),
	CONSTRAINT FK_ID_IMPUESTO_ITEM FOREIGN KEY (ID_IMPUESTO)
		REFERENCES TBL_IMPUESTO(ID),
	CONSTRAINT FK_ID_FOTO_ITEM FOREIGN KEY (ID_FOTO)
		REFERENCES TBL_ARCHIVOS(ID)
)

--TABLA CALIFICACIONES
CREATE TABLE TBL_CALIFICACIONES(
	ID INT IDENTITY(1,1),
	ID_USUARIO INT,
	CALIFICACION INT,
	ID_COMERCIO INT,
	ID_ITEM INT,
	CONSTRAINT PK_ID_CALIFICACIONES PRIMARY KEY CLUSTERED(ID),
	CONSTRAINT FK_ID_USUARIO_CALIFICACIONES FOREIGN KEY(ID_USUARIO)
		REFERENCES TBL_USUARIO(ID),
	CONSTRAINT FK_ID_COMERCIO_CALIFICACIONES FOREIGN KEY(ID_COMERCIO)
		REFERENCES TBL_COMERCIO(ID),
	CONSTRAINT FK_ID_ITEM_CALIFICACIONES FOREIGN KEY (ID_ITEM)
		REFERENCES TBL_ITEM(ID)
)

--TABLA VISTA
CREATE TABLE TBL_VISTA(
	ID INT IDENTITY(1,1),
	NOMBRE NVARCHAR(30),
	CONSTRAINT PK_ID_VISTA PRIMARY KEY CLUSTERED(ID)
)

--TABLA ROL
CREATE TABLE TBL_ROL(
	ID INT IDENTITY(1,1),
	NOMBRE NVARCHAR(25),
	DESCRIPCION NVARCHAR(300),
	ID_COMERCIO INT,
	CONSTRAINT PK_ID_ROL PRIMARY KEY CLUSTERED (ID),
	CONSTRAINT FK_ID_COMERCIO_ROL FOREIGN KEY(ID_COMERCIO)
		REFERENCES TBL_COMERCIO(ID)
)

--TABLA VISTAXROL
CREATE TABLE TBL_VISTAXROL(
	ID INT IDENTITY(1,1),
	ID_VISTA INT, 
	ID_ROL INT,
	CONSTRAINT PK_ID_PERMISOS PRIMARY KEY CLUSTERED(ID),
	CONSTRAINT FK_ID_VISTA_VISTAXROL FOREIGN KEY(ID_VISTA)
		REFERENCES TBL_VISTA(ID),
	CONSTRAINT FK_ID_ROL_VISTAXROL FOREIGN KEY(ID_ROL)
		REFERENCES TBL_ROL(ID)
)

--TABLA EMPLEADO
CREATE TABLE TBL_EMPLEADO(
	ID INT IDENTITY(1,1),
	ID_USUARIO INT,
	ID_ROL INT,
	ID_SUCURSAL INT,
	CONSTRAINT PK_ID_EMPLEADO PRIMARY KEY CLUSTERED (ID),
	CONSTRAINT FK_ID_USUARIO_EMPLEADO FOREIGN KEY(ID_USUARIO)
		REFERENCES TBL_USUARIO(ID),
	CONSTRAINT FK_ID_ROL_EMPLEADO FOREIGN KEY(ID_ROL)
		REFERENCES TBL_ROL(ID),
	CONSTRAINT FK_ID_SUCURSAL_EMPLEADO FOREIGN KEY(ID_SUCURSAL)
		REFERENCES TBL_SUCURSAL(ID)
)

--TABLA CATEGORIA
CREATE TABLE TBL_CATEGORIA(
	ID INT IDENTITY(1,1),
	NOMBRE NVARCHAR(25),
	CONSTRAINT PK_ID_CATEGORIA PRIMARY KEY CLUSTERED(ID)
)

CREATE UNIQUE NONCLUSTERED INDEX IX_NOMBRE_CATEGORIA ON TBL_CATEGORIA(NOMBRE)

--TABLA CATEGORIAXCOMERCIO
CREATE TABLE TBL_CATEGORIAXCOMERCIO(
	ID INT IDENTITY(1,1),
	ID_COMERCIO INT,
	ID_CATEGORIA INT,
	CONSTRAINT PK_ID_CATEGORIAXCOMERCIO PRIMARY KEY CLUSTERED(ID),
	CONSTRAINT FK_ID_COMERCIO_CATEGORIAXCOMERCIO FOREIGN KEY(ID_COMERCIO)
		REFERENCES TBL_COMERCIO(ID),
	CONSTRAINT FK_ID_CATEGORIA_CATEGORIAXCOMERCIO FOREIGN KEY(ID_CATEGORIA)
		REFERENCES TBL_CATEGORIA(ID)
)

--TABLA LISTA_DESEO
CREATE TABLE TBL_LISTA_DESEO(
	ID INT IDENTITY(1,1),
	FECHA_CREACION DATE,
	ID_USUARIO INT,
	CONSTRAINT PK_ID_LISTA_DESEO PRIMARY KEY CLUSTERED(ID),
	CONSTRAINT FK_ID_USUARIO_LISTA_DESEO FOREIGN KEY(ID)
		REFERENCES TBL_USUARIO(ID)
)

--TABLA ITEMXLISTA
CREATE TABLE TBL_ITEMXLISTA(
	ID INT IDENTITY(1,1),
	ID_LISTA_DESEO INT,
	ID_ITEM INT,
	CONSTRAINT PK_ID_ITEMXLISTA PRIMARY KEY CLUSTERED(ID),
	CONSTRAINT FK_ID_LISTA_DESEO_ITEMXLISTA FOREIGN KEY(ID_LISTA_DESEO)
		REFERENCES TBL_LISTA_DESEO(ID),
	CONSTRAINT FK_ID_ITEM_ITEMXLISTA FOREIGN KEY(ID_ITEM)
		REFERENCES TBL_ITEM(ID)
)

--TABLA CITA
CREATE TABLE TBL_CITA(
	ID INT IDENTITY(1,1),
	ID_ITEM INT,
	ID_CLIENTE INT,
	ID_EMPLEADO INT,
	ID_HORARIO INT,
	CONSTRAINT PK_ID_CITA PRIMARY KEY CLUSTERED(ID),
	CONSTRAINT FK_ID_ITEM_CITA FOREIGN KEY (ID_ITEM)
		REFERENCES TBL_ITEM(ID),
	CONSTRAINT FK_ID_CLIENTE_CITA FOREIGN KEY(ID_CLIENTE)
		REFERENCES TBL_USUARIO(ID),
	CONSTRAINT FK_ID_EMPLEADO_CITA FOREIGN KEY(ID_EMPLEADO)
		REFERENCES TBL_EMPLEADO(ID),
	CONSTRAINT FK_ID_HORARIO_CITA FOREIGN KEY(ID_HORARIO)
		REFERENCES TBL_HORARIO(ID)
)

--TABLA PROMOCION
CREATE TABLE TBL_PROMOCION(
	ID INT IDENTITY(1,1),
	NOMBRE NVARCHAR(15),
	PORCENTAJE DECIMAL(4,2),
	CODIGO NVARCHAR(15),
	CANTIDAD INT,
	ID_COMERCIO INT,
	ID_SUCURSAL INT,
	CONSTRAINT PK_ID_DESCUENTO PRIMARY KEY CLUSTERED(ID),
	CONSTRAINT FK_ID_COMERCIO_PROMOCION FOREIGN KEY(ID_COMERCIO)
		REFERENCES TBL_COMERCIO(ID),
	CONSTRAINT FK_ID_SUCURSAL_PROMOCION FOREIGN KEY(ID_SUCURSAL)
		REFERENCES TBL_SUCURSAL(ID)
)

--TABLA TRANSACCION
CREATE TABLE TBL_TRANSACCION(
	ID INT IDENTITY(1,1),
	CODIGO_CONFIRMACION VARCHAR(200),
	TIPO_PAGO VARCHAR(10),
	MONTO DECIMAL(10,2),
	CONSTRAINT PK_ID_TRANSACCION PRIMARY KEY CLUSTERED(ID)
)

--TABLA FACTURA
CREATE TABLE TBL_FACTURA(
	ID INT IDENTITY(1,1),
	FECHA DATE,
	ID_USUARIO INT,
	ID_EMPLEADO INT,
	NOMBRE_EMPLEADO NVARCHAR(25),
	APELLIDO_EMPLEADO NVARCHAR(25),
	CEDULA_USUARIO NVARCHAR(30),
	NOMBRE_USUARIO NVARCHAR(25),
	APELLIDO_USUARIO NVARCHAR(50),
	TELEFONO_USUARIO NVARCHAR(30),
	CORREO_USUARIO NVARCHAR(100),
	NOMBRE_PROVINCIA NVARCHAR(30),
	NOMBRE_CANTON NVARCHAR(30),
	NOMBRE_DISTRITO NVARCHAR(30),
	DETALLES_DIRECCION NVARCHAR(150),
	NOMBRE_SUCURSAL NVARCHAR(30),
	CEDULA_JURIDICA NVARCHAR(50),
	ID_TRANSACCION INT,
	ID_PROMOCION INT,
	NOMBRE_PROMOCION NVARCHAR(15),
	PORCENTAJE DECIMAL(4,2),
	CONSTRAINT PK_ID_FACTURA PRIMARY KEY CLUSTERED(ID),
	CONSTRAINT FK_ID_USUARIO_FACTURA FOREIGN KEY(ID_USUARIO)
		REFERENCES TBL_USUARIO(ID),
	CONSTRAINT FK_ID_EMPLEADO_FACTURA FOREIGN KEY(ID_EMPLEADO)
		REFERENCES TBL_EMPLEADO(ID),
	CONSTRAINT FK_ID_TRANSACCION_FACTURA FOREIGN KEY(ID_TRANSACCION)
		REFERENCES TBL_TRANSACCION(ID),
	CONSTRAINT FK_ID_PROMOCION_FACTURA FOREIGN KEY(ID_PROMOCION)
		REFERENCES TBL_PROMOCION(ID),
)

---TABLA LINEA FACTURA
CREATE TABLE TBL_LINEA_FACTURA(
	ID INT IDENTITY(1,1),
	ID_ITEM INT,
	NOMBRE_ITEM NVARCHAR(15),
	CANTIDAD_ITEM INT,
	PRECIO_ITEM DECIMAL(10,2),
	IMPUESTO DECIMAL(4,2),
	ID_FACTURA INT,
	CONSTRAINT PK_ID_LINEA_FACTURA PRIMARY KEY CLUSTERED(ID),
	CONSTRAINT FK_ID_ITEM_LINEA_FACTURA FOREIGN KEY(ID_ITEM)
		REFERENCES TBL_ITEM(ID),
	CONSTRAINT FK_ID_FACTURA_LINEA_FACTURA FOREIGN KEY(ID_FACTURA)
		REFERENCES TBL_FACTURA(ID)
)


--TABLA BITACORA
CREATE TABLE BITACORA(
	ID INT IDENTITY(1,1),
	FECHA DATETIME, 
	ACCION NVARCHAR(50),
	ID_USUARIO INT,
	CONSTRAINT PK_ID_BITACORA PRIMARY KEY CLUSTERED(ID),
	CONSTRAINT FK_ID_USUARIO_BITACORA FOREIGN KEY(ID_USUARIO)
		REFERENCES TBL_USUARIO(ID)
)



